### ISSUE TITLE
apiInit not defined error

### ISSUE THREAD

**Issue by jacobhinkle** [Arceliar/bmwrapper#1]
I run python main.py and bmwrapper starts up fine.  When I try to send a message over SMTP (through thunderbird), the console spits out the following:

```
error: uncaptured python exception, closing channel <smtpd.SMTPChannel connected 127.0.0.1:33541 at 0xca15a8> (<type 'exceptions.NameError'>:global name 'apiInit' is not defined [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|449] [/usr/lib/python2.7/asynchat.py|handle_read|158] [/usr/lib/python2.7/smtpd.py|found_terminator|181] [/home/jacob/src/bmwrapper/outgoing.py|process_message|23] [/home/jacob/src/bmwrapper/bminterface.py|send|68] [/home/jacob/src/bmwrapper/bminterface.py|_sendBroadcast|40] [/home/jacob/src/bmwrapper/bminterface.py|_makeApi|30] [/home/jacob/src/bmwrapper/bminterface.py|_getConfig|15] [/home/jacob/src/bmwrapper/bminterface.py|apiData|185])
```

It seems bmwrapper is missing `apiInit`.

**Comment by Arceliar** [comment]
Temporary "fix" committed.

This happens because your API isn't configured. I'm hesitant to go changing people's keys.dat file for the time being. I've changed it such that it will still crash, but first it will explain that the API isn't configured, and point to the relevant wiki page.

**Comment by jacobhinkle** [comment]
Great.  Didn't realize I needed to do that, and also to start PyBitmessage in the background.  Working great now. Thanks a lot
