### ISSUE TITLE
bmwrapper crashes when attempting to download messages

### ISSUE THREAD

**Issue by justusranvier** [Arceliar/bmwrapper#7]
When attempting to poll bmwrapper using fetchmail this happens:

<pre>2014-01-13 11:03:44,172 INFO - Press Ctrl+C to exit.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/bmwrapper/incoming.py", line 248, in incomingServer_main
    sock.close()
AttributeError: 'NoneType' object has no attribute 'close'</pre>

**Comment by justusranvier** [comment]
Relevant lines from fetchmail logs:

<pre>Jan 13 17:50:58 [fetchmail] Trying to connect to 192.168.135.18/110...connected._
Jan 13 17:50:58 [fetchmail] POP3&lt; +OK server ready_
Jan 13 17:50:58 [fetchmail] POP3&gt; CAPA_
Jan 13 17:50:58 [fetchmail] POP3&lt; -ERR unknown command_
Jan 13 17:50:58 [fetchmail] unknown command_</pre>

**Comment by ghost** [comment]
https://github.com/Arceliar/bmwrapper/pull/8

**Comment by justusranvier** [comment]
Using that branch I get a different error for bmwrapper:

<pre>2014-01-13 18:08:41,090 INFO - Press Ctrl+C to exit.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/bmwrapper/incoming.py", line 230, in incomingServer_main
    data = conn.recvall()
  File "/usr/lib64/python2.7/site-packages/bmwrapper/incoming.py", line 28, in recvall
    data.append(chunk)
MemoryError</pre>

**Comment by justusranvier** [comment]
Despite what the Fetchmail FAQ says, there's no way to disable the CAPA check. However, if it fails the first time it polls a server, then it will stop asking for it.

So if I restart bmwrapper after it's crashed once, then I'll get different behavior. It almost works, but somehow fails to actually download messages:

<pre>2014-01-13 18:18:49,037 INFO - Press Ctrl+C to exit.
2014-01-13 18:19:37,519 DEBUG - Parsing msg 1 of 1
2014-01-13 18:19:37,520 DEBUG - Answering STAT: 1 409
2014-01-13 18:19:37,521 DEBUG - Parsing msg 1 of 1
2014-01-13 18:19:37,521 DEBUG - Answering LIST: 1 409</pre>

<pre>Jan 13 18:19:37 [fetchmail] awakened at Mon 13 Jan 2014 06:19:37 PM UTC_
Jan 13 18:19:37 [fetchmail] 6.3.26 querying argon (protocol POP3) at Mon 13 Jan 2014 06:19:37 PM UTC: poll started_
Jan 13 18:19:37 [fetchmail] Trying to connect to 192.168.135.18/110...connected._
Jan 13 18:19:37 [fetchmail] POP3&lt; +OK server ready_
Jan 13 18:19:37 [fetchmail] POP3&gt; USER justus_
Jan 13 18:19:37 [fetchmail] POP3&lt; +OK user accepted_
Jan 13 18:19:37 [fetchmail] POP3&gt; PASS *_
Jan 13 18:19:37 [fetchmail] POP3&lt; +OK pass accepted_
Jan 13 18:19:37 [fetchmail] selecting or re-polling default folder_
Jan 13 18:19:37 [fetchmail] POP3&gt; STAT_
Jan 13 18:19:37 [fetchmail] POP3&lt; +OK 1 409_
Jan 13 18:19:37 [fetchmail] 1 message for justus at argon (409 octets)._
Jan 13 18:19:37 [fetchmail] POP3&gt; LIST 1_
Jan 13 18:19:37 [fetchmail] POP3&lt; _
Jan 13 18:19:37 [fetchmail] POP3&gt; QUIT_
Jan 13 18:19:37 [fetchmail] POP3&lt; +OK 1 messages (409 octets)_
Jan 13 18:19:37 [fetchmail] client/server protocol error while fetching from justus@argon_
Jan 13 18:19:37 [fetchmail] 6.3.26 querying argon (protocol POP3) at Mon 13 Jan 2014 06:19:37 PM UTC: poll completed_
Jan 13 18:19:37 [fetchmail] Merged UID list from argon: &lt;empty&gt;_
Jan 13 18:19:37 [fetchmail] Query status=4 (PROTOCOL)_
Jan 13 18:19:37 [fetchmail] sleeping at Mon 13 Jan 2014 06:19:37 PM UTC for 60 seconds_</pre>

**Comment by Arceliar** [comment]
I must admit, I've not used fetchmail at all.

bmwrapper mostly just implements the subset of POP needed to make it play (sort-of) nice with thunderbird. It looks like it's first requesting a LIST of the inbox, followed by something bmwrapper doesn't understand and likely ignores.

I'll try to find time this weekend to setup fetchmail and see what it's doing. Hopefully it'll just require another simple handler to fix.

**Comment by justusranvier** [comment]
Jimmysong's branch fixes this issue for me.
